/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.tvshows.model

import com.google.gson.annotations.SerializedName
import io.swagger.v3.oas.annotations.media.Schema
import java.util.*

/**
 * Cast
 */
class Cast {
    /**
     * Get person
     * @return person
     */
    @get:Schema(required = true, description = "")
    @SerializedName("person")
    var person: Person? = null

    /**
     * Get character
     * @return character
     */
    @get:Schema(required = true, description = "")
    @SerializedName("character")
    var character: Character? = null

    /**
     * Get self
     * @return self
     */
    @get:Schema(required = true, description = "")
    @SerializedName("self")
    var isSelf: Boolean? = null

    /**
     * Get voice
     * @return voice
     */
    @get:Schema(required = true, description = "")
    @SerializedName("voice")
    var isVoice: Boolean? = null
    fun person(person: Person?): Cast {
        this.person = person
        return this
    }

    fun character(character: Character?): Cast {
        this.character = character
        return this
    }

    fun self(self: Boolean?): Cast {
        isSelf = self
        return this
    }

    fun voice(voice: Boolean?): Cast {
        isVoice = voice
        return this
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null || javaClass != other.javaClass) {
            return false
        }
        val cast = other as Cast
        return person == cast.person &&
                character == cast.character &&
                isSelf == cast.isSelf &&
                isVoice == cast.isVoice
    }

    override fun hashCode(): Int {
        return Objects.hash(person, character, isSelf, isVoice)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class Cast {\n")
        sb.append("    person: ").append(toIndentedString(person)).append("\n")
        sb.append("    character: ").append(toIndentedString(character)).append("\n")
        sb.append("    self: ").append(toIndentedString(isSelf)).append("\n")
        sb.append("    voice: ").append(toIndentedString(isVoice)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}