/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.bme.aut.tvshows.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CastData
 */

public class CastData {
  @SerializedName("personId")
  private Integer personId = null;

  @SerializedName("character")
  private CharacterData character = null;

  @SerializedName("self")
  private Boolean self = null;

  @SerializedName("voice")
  private Boolean voice = null;

  public CastData personId(Integer personId) {
    this.personId = personId;
    return this;
  }

   /**
   * Get personId
   * @return personId
  **/
  @Schema(description = "")
  public Integer getPersonId() {
    return personId;
  }

  public void setPersonId(Integer personId) {
    this.personId = personId;
  }

  public CastData character(CharacterData character) {
    this.character = character;
    return this;
  }

   /**
   * Get character
   * @return character
  **/
  @Schema(description = "")
  public CharacterData getCharacter() {
    return character;
  }

  public void setCharacter(CharacterData character) {
    this.character = character;
  }

  public CastData self(Boolean self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @Schema(description = "")
  public Boolean isSelf() {
    return self;
  }

  public void setSelf(Boolean self) {
    this.self = self;
  }

  public CastData voice(Boolean voice) {
    this.voice = voice;
    return this;
  }

   /**
   * Get voice
   * @return voice
  **/
  @Schema(description = "")
  public Boolean isVoice() {
    return voice;
  }

  public void setVoice(Boolean voice) {
    this.voice = voice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CastData castData = (CastData) o;
    return Objects.equals(this.personId, castData.personId) &&
        Objects.equals(this.character, castData.character) &&
        Objects.equals(this.self, castData.self) &&
        Objects.equals(this.voice, castData.voice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personId, character, self, voice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CastData {\n");
    
    sb.append("    personId: ").append(toIndentedString(personId)).append("\n");
    sb.append("    character: ").append(toIndentedString(character)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    voice: ").append(toIndentedString(voice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
