/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.tvshows.model

import com.google.gson.annotations.SerializedName
import io.swagger.v3.oas.annotations.media.Schema
import java.util.*

/**
 * CastData
 */
class CastData {
    /**
     * Get personId
     * @return personId
     */
    @get:Schema(description = "")
    @SerializedName("personId")
    var personId: Int? = null

    /**
     * Get character
     * @return character
     */
    @get:Schema(description = "")
    @SerializedName("character")
    var character: CharacterData? = null

    /**
     * Get self
     * @return self
     */
    @get:Schema(description = "")
    @SerializedName("self")
    var isSelf: Boolean? = null

    /**
     * Get voice
     * @return voice
     */
    @get:Schema(description = "")
    @SerializedName("voice")
    var isVoice: Boolean? = null
    fun personId(personId: Int?): CastData {
        this.personId = personId
        return this
    }

    fun character(character: CharacterData?): CastData {
        this.character = character
        return this
    }

    fun self(self: Boolean?): CastData {
        isSelf = self
        return this
    }

    fun voice(voice: Boolean?): CastData {
        isVoice = voice
        return this
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null || javaClass != other.javaClass) {
            return false
        }
        val castData = other as CastData
        return personId == castData.personId &&
                character == castData.character &&
                isSelf == castData.isSelf &&
                isVoice == castData.isVoice
    }

    override fun hashCode(): Int {
        return Objects.hash(personId, character, isSelf, isVoice)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class CastData {\n")
        sb.append("    personId: ").append(toIndentedString(personId)).append("\n")
        sb.append("    character: ").append(toIndentedString(character)).append("\n")
        sb.append("    self: ").append(toIndentedString(isSelf)).append("\n")
        sb.append("    voice: ").append(toIndentedString(isVoice)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}