/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.tvshows.model

import com.google.gson.annotations.SerializedName
import io.swagger.v3.oas.annotations.media.Schema
import java.math.BigDecimal
import java.util.*

/**
 * Character
 */
class Character {
    /**
     * Get id
     * @return id
     */
    @get:Schema(required = true, description = "")
    @SerializedName("id")
    var id: BigDecimal? = null

    /**
     * Get url
     * @return url
     */
    @get:Schema(required = true, description = "")
    @SerializedName("url")
    var url: String? = null

    /**
     * Get name
     * @return name
     */
    @get:Schema(required = true, description = "")
    @SerializedName("name")
    var name: String? = null

    /**
     * Get image
     * @return image
     */
    @get:Schema(description = "")
    @SerializedName("image")
    var image: Image? = null

    /**
     * Get _links
     * @return _links
     */
    @get:Schema(required = true, description = "")
    @SerializedName("_links")
    var links: Links? = null
    fun id(id: BigDecimal?): Character {
        this.id = id
        return this
    }

    fun url(url: String?): Character {
        this.url = url
        return this
    }

    fun name(name: String?): Character {
        this.name = name
        return this
    }

    fun image(image: Image?): Character {
        this.image = image
        return this
    }

    fun _links(_links: Links?): Character {
        links = _links
        return this
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null || javaClass != other.javaClass) {
            return false
        }
        val character = other as Character
        return id == character.id &&
                url == character.url &&
                name == character.name &&
                image == character.image &&
                links == character.links
    }

    override fun hashCode(): Int {
        return Objects.hash(id, url, name, image, links)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class Character {\n")
        sb.append("    id: ").append(toIndentedString(id)).append("\n")
        sb.append("    url: ").append(toIndentedString(url)).append("\n")
        sb.append("    name: ").append(toIndentedString(name)).append("\n")
        sb.append("    image: ").append(toIndentedString(image)).append("\n")
        sb.append("    _links: ").append(toIndentedString(links)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}