/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.tvshows.model

import com.google.gson.annotations.SerializedName
import io.swagger.v3.oas.annotations.media.Schema
import java.util.*

/**
 * CharacterData
 */
class CharacterData {
    /**
     * Get name
     * @return name
     */
    @get:Schema(required = true, description = "")
    @SerializedName("name")
    var name: String? = null

    /**
     * Get image
     * @return image
     */
    @get:Schema(required = true, description = "")
    @SerializedName("image")
    var image: Image? = null
    fun name(name: String?): CharacterData {
        this.name = name
        return this
    }

    fun image(image: Image?): CharacterData {
        this.image = image
        return this
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null || javaClass != other.javaClass) {
            return false
        }
        val characterData = other as CharacterData
        return name == characterData.name &&
                image == characterData.image
    }

    override fun hashCode(): Int {
        return Objects.hash(name, image)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class CharacterData {\n")
        sb.append("    name: ").append(toIndentedString(name)).append("\n")
        sb.append("    image: ").append(toIndentedString(image)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}