/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.bme.aut.tvshows.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Episode
 */

public class Episode {
  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("season")
  private BigDecimal season = null;

  @SerializedName("number")
  private BigDecimal number = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("airdate")
  private String airdate = null;

  @SerializedName("airtime")
  private String airtime = null;

  @SerializedName("airstamp")
  private String airstamp = null;

  @SerializedName("runtime")
  private BigDecimal runtime = null;

  @SerializedName("image")
  private Image image = null;

  @SerializedName("summary")
  private String summary = null;

  @SerializedName("_links")
  private Links _links = null;

  public Episode id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public Episode url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(required = true, description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Episode name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Episode season(BigDecimal season) {
    this.season = season;
    return this;
  }

   /**
   * Get season
   * @return season
  **/
  @Schema(required = true, description = "")
  public BigDecimal getSeason() {
    return season;
  }

  public void setSeason(BigDecimal season) {
    this.season = season;
  }

  public Episode number(BigDecimal number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @Schema(required = true, description = "")
  public BigDecimal getNumber() {
    return number;
  }

  public void setNumber(BigDecimal number) {
    this.number = number;
  }

  public Episode type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Episode airdate(String airdate) {
    this.airdate = airdate;
    return this;
  }

   /**
   * Get airdate
   * @return airdate
  **/
  @Schema(required = true, description = "")
  public String getAirdate() {
    return airdate;
  }

  public void setAirdate(String airdate) {
    this.airdate = airdate;
  }

  public Episode airtime(String airtime) {
    this.airtime = airtime;
    return this;
  }

   /**
   * Get airtime
   * @return airtime
  **/
  @Schema(required = true, description = "")
  public String getAirtime() {
    return airtime;
  }

  public void setAirtime(String airtime) {
    this.airtime = airtime;
  }

  public Episode airstamp(String airstamp) {
    this.airstamp = airstamp;
    return this;
  }

   /**
   * Get airstamp
   * @return airstamp
  **/
  @Schema(required = true, description = "")
  public String getAirstamp() {
    return airstamp;
  }

  public void setAirstamp(String airstamp) {
    this.airstamp = airstamp;
  }

  public Episode runtime(BigDecimal runtime) {
    this.runtime = runtime;
    return this;
  }

   /**
   * Get runtime
   * @return runtime
  **/
  @Schema(required = true, description = "")
  public BigDecimal getRuntime() {
    return runtime;
  }

  public void setRuntime(BigDecimal runtime) {
    this.runtime = runtime;
  }

  public Episode image(Image image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @Schema(description = "")
  public Image getImage() {
    return image;
  }

  public void setImage(Image image) {
    this.image = image;
  }

  public Episode summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @Schema(required = true, description = "")
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public Episode _links(Links _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(required = true, description = "")
  public Links getLinks() {
    return _links;
  }

  public void setLinks(Links _links) {
    this._links = _links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Episode episode = (Episode) o;
    return Objects.equals(this.id, episode.id) &&
        Objects.equals(this.url, episode.url) &&
        Objects.equals(this.name, episode.name) &&
        Objects.equals(this.season, episode.season) &&
        Objects.equals(this.number, episode.number) &&
        Objects.equals(this.type, episode.type) &&
        Objects.equals(this.airdate, episode.airdate) &&
        Objects.equals(this.airtime, episode.airtime) &&
        Objects.equals(this.airstamp, episode.airstamp) &&
        Objects.equals(this.runtime, episode.runtime) &&
        Objects.equals(this.image, episode.image) &&
        Objects.equals(this.summary, episode.summary) &&
        Objects.equals(this._links, episode._links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, name, season, number, type, airdate, airtime, airstamp, runtime, image, summary, _links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Episode {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    season: ").append(toIndentedString(season)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    airdate: ").append(toIndentedString(airdate)).append("\n");
    sb.append("    airtime: ").append(toIndentedString(airtime)).append("\n");
    sb.append("    airstamp: ").append(toIndentedString(airstamp)).append("\n");
    sb.append("    runtime: ").append(toIndentedString(runtime)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
