/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.tvshows.model

import com.google.gson.annotations.SerializedName
import io.swagger.v3.oas.annotations.media.Schema
import java.math.BigDecimal
import java.util.*

/**
 * EpisodeData
 */
class EpisodeData {
    /**
     * Get name
     * @return name
     */
    @get:Schema(required = true, description = "")
    @SerializedName("name")
    var name: String? = null

    /**
     * Get season
     * @return season
     */
    @get:Schema(required = true, description = "")
    @SerializedName("season")
    var season: BigDecimal? = null

    /**
     * Get number
     * @return number
     */
    @get:Schema(required = true, description = "")
    @SerializedName("number")
    var number: BigDecimal? = null

    /**
     * Get type
     * @return type
     */
    @get:Schema(required = true, description = "")
    @SerializedName("type")
    var type: String? = null

    /**
     * Get airdate
     * @return airdate
     */
    @get:Schema(required = true, description = "")
    @SerializedName("airdate")
    var airdate: String? = null

    /**
     * Get airtime
     * @return airtime
     */
    @get:Schema(required = true, description = "")
    @SerializedName("airtime")
    var airtime: String? = null

    /**
     * Get airstamp
     * @return airstamp
     */
    @get:Schema(required = true, description = "")
    @SerializedName("airstamp")
    var airstamp: String? = null

    /**
     * Get runtime
     * @return runtime
     */
    @get:Schema(required = true, description = "")
    @SerializedName("runtime")
    var runtime: BigDecimal? = null

    /**
     * Get image
     * @return image
     */
    @get:Schema(required = true, description = "")
    @SerializedName("image")
    var image: Image? = null

    /**
     * Get summary
     * @return summary
     */
    @get:Schema(required = true, description = "")
    @SerializedName("summary")
    var summary: String? = null
    fun name(name: String?): EpisodeData {
        this.name = name
        return this
    }

    fun season(season: BigDecimal?): EpisodeData {
        this.season = season
        return this
    }

    fun number(number: BigDecimal?): EpisodeData {
        this.number = number
        return this
    }

    fun type(type: String?): EpisodeData {
        this.type = type
        return this
    }

    fun airdate(airdate: String?): EpisodeData {
        this.airdate = airdate
        return this
    }

    fun airtime(airtime: String?): EpisodeData {
        this.airtime = airtime
        return this
    }

    fun airstamp(airstamp: String?): EpisodeData {
        this.airstamp = airstamp
        return this
    }

    fun runtime(runtime: BigDecimal?): EpisodeData {
        this.runtime = runtime
        return this
    }

    fun image(image: Image?): EpisodeData {
        this.image = image
        return this
    }

    fun summary(summary: String?): EpisodeData {
        this.summary = summary
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val episodeData = o as EpisodeData
        return name == episodeData.name &&
                season == episodeData.season &&
                number == episodeData.number &&
                type == episodeData.type &&
                airdate == episodeData.airdate &&
                airtime == episodeData.airtime &&
                airstamp == episodeData.airstamp &&
                runtime == episodeData.runtime &&
                image == episodeData.image &&
                summary == episodeData.summary
    }

    override fun hashCode(): Int {
        return Objects.hash(
            name,
            season,
            number,
            type,
            airdate,
            airtime,
            airstamp,
            runtime,
            image,
            summary
        )
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class EpisodeData {\n")
        sb.append("    name: ").append(toIndentedString(name)).append("\n")
        sb.append("    season: ").append(toIndentedString(season)).append("\n")
        sb.append("    number: ").append(toIndentedString(number)).append("\n")
        sb.append("    type: ").append(toIndentedString(type)).append("\n")
        sb.append("    airdate: ").append(toIndentedString(airdate)).append("\n")
        sb.append("    airtime: ").append(toIndentedString(airtime)).append("\n")
        sb.append("    airstamp: ").append(toIndentedString(airstamp)).append("\n")
        sb.append("    runtime: ").append(toIndentedString(runtime)).append("\n")
        sb.append("    image: ").append(toIndentedString(image)).append("\n")
        sb.append("    summary: ").append(toIndentedString(summary)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}