/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.bme.aut.tvshows.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * EpisodeData
 */

public class EpisodeData {
  @SerializedName("name")
  private String name = null;

  @SerializedName("season")
  private BigDecimal season = null;

  @SerializedName("number")
  private BigDecimal number = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("airdate")
  private String airdate = null;

  @SerializedName("airtime")
  private String airtime = null;

  @SerializedName("airstamp")
  private String airstamp = null;

  @SerializedName("runtime")
  private BigDecimal runtime = null;

  @SerializedName("image")
  private Image image = null;

  @SerializedName("summary")
  private String summary = null;

  public EpisodeData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EpisodeData season(BigDecimal season) {
    this.season = season;
    return this;
  }

   /**
   * Get season
   * @return season
  **/
  @Schema(required = true, description = "")
  public BigDecimal getSeason() {
    return season;
  }

  public void setSeason(BigDecimal season) {
    this.season = season;
  }

  public EpisodeData number(BigDecimal number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @Schema(required = true, description = "")
  public BigDecimal getNumber() {
    return number;
  }

  public void setNumber(BigDecimal number) {
    this.number = number;
  }

  public EpisodeData type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public EpisodeData airdate(String airdate) {
    this.airdate = airdate;
    return this;
  }

   /**
   * Get airdate
   * @return airdate
  **/
  @Schema(required = true, description = "")
  public String getAirdate() {
    return airdate;
  }

  public void setAirdate(String airdate) {
    this.airdate = airdate;
  }

  public EpisodeData airtime(String airtime) {
    this.airtime = airtime;
    return this;
  }

   /**
   * Get airtime
   * @return airtime
  **/
  @Schema(required = true, description = "")
  public String getAirtime() {
    return airtime;
  }

  public void setAirtime(String airtime) {
    this.airtime = airtime;
  }

  public EpisodeData airstamp(String airstamp) {
    this.airstamp = airstamp;
    return this;
  }

   /**
   * Get airstamp
   * @return airstamp
  **/
  @Schema(required = true, description = "")
  public String getAirstamp() {
    return airstamp;
  }

  public void setAirstamp(String airstamp) {
    this.airstamp = airstamp;
  }

  public EpisodeData runtime(BigDecimal runtime) {
    this.runtime = runtime;
    return this;
  }

   /**
   * Get runtime
   * @return runtime
  **/
  @Schema(required = true, description = "")
  public BigDecimal getRuntime() {
    return runtime;
  }

  public void setRuntime(BigDecimal runtime) {
    this.runtime = runtime;
  }

  public EpisodeData image(Image image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @Schema(required = true, description = "")
  public Image getImage() {
    return image;
  }

  public void setImage(Image image) {
    this.image = image;
  }

  public EpisodeData summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @Schema(required = true, description = "")
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EpisodeData episodeData = (EpisodeData) o;
    return Objects.equals(this.name, episodeData.name) &&
        Objects.equals(this.season, episodeData.season) &&
        Objects.equals(this.number, episodeData.number) &&
        Objects.equals(this.type, episodeData.type) &&
        Objects.equals(this.airdate, episodeData.airdate) &&
        Objects.equals(this.airtime, episodeData.airtime) &&
        Objects.equals(this.airstamp, episodeData.airstamp) &&
        Objects.equals(this.runtime, episodeData.runtime) &&
        Objects.equals(this.image, episodeData.image) &&
        Objects.equals(this.summary, episodeData.summary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, season, number, type, airdate, airtime, airstamp, runtime, image, summary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EpisodeData {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    season: ").append(toIndentedString(season)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    airdate: ").append(toIndentedString(airdate)).append("\n");
    sb.append("    airtime: ").append(toIndentedString(airtime)).append("\n");
    sb.append("    airstamp: ").append(toIndentedString(airstamp)).append("\n");
    sb.append("    runtime: ").append(toIndentedString(runtime)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
