/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.bme.aut.tvshows.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Externals
 */

public class Externals {
  @SerializedName("tvrage")
  private BigDecimal tvrage = null;

  @SerializedName("thetvdb")
  private BigDecimal thetvdb = null;

  @SerializedName("imdb")
  private String imdb = null;

  public Externals tvrage(BigDecimal tvrage) {
    this.tvrage = tvrage;
    return this;
  }

   /**
   * Get tvrage
   * @return tvrage
  **/
  @Schema(description = "")
  public BigDecimal getTvrage() {
    return tvrage;
  }

  public void setTvrage(BigDecimal tvrage) {
    this.tvrage = tvrage;
  }

  public Externals thetvdb(BigDecimal thetvdb) {
    this.thetvdb = thetvdb;
    return this;
  }

   /**
   * Get thetvdb
   * @return thetvdb
  **/
  @Schema(description = "")
  public BigDecimal getThetvdb() {
    return thetvdb;
  }

  public void setThetvdb(BigDecimal thetvdb) {
    this.thetvdb = thetvdb;
  }

  public Externals imdb(String imdb) {
    this.imdb = imdb;
    return this;
  }

   /**
   * Get imdb
   * @return imdb
  **/
  @Schema(description = "")
  public String getImdb() {
    return imdb;
  }

  public void setImdb(String imdb) {
    this.imdb = imdb;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Externals externals = (Externals) o;
    return Objects.equals(this.tvrage, externals.tvrage) &&
        Objects.equals(this.thetvdb, externals.thetvdb) &&
        Objects.equals(this.imdb, externals.imdb);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tvrage, thetvdb, imdb);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Externals {\n");
    
    sb.append("    tvrage: ").append(toIndentedString(tvrage)).append("\n");
    sb.append("    thetvdb: ").append(toIndentedString(thetvdb)).append("\n");
    sb.append("    imdb: ").append(toIndentedString(imdb)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
