/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.tvshows.model

import com.google.gson.annotations.SerializedName
import io.swagger.v3.oas.annotations.media.Schema
import java.util.*

/**
 * Image
 */
class Image {
    /**
     * Get medium
     * @return medium
     */
    @get:Schema(required = true, description = "")
    @SerializedName("medium")
    var medium: String? = null

    /**
     * Get original
     * @return original
     */
    @get:Schema(required = true, description = "")
    @SerializedName("original")
    var original: String? = null
    fun medium(medium: String?): Image {
        this.medium = medium
        return this
    }

    fun original(original: String?): Image {
        this.original = original
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val image = o as Image
        return medium == image.medium &&
                original == image.original
    }

    override fun hashCode(): Int {
        return Objects.hash(medium, original)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class Image {\n")
        sb.append("    medium: ").append(toIndentedString(medium)).append("\n")
        sb.append("    original: ").append(toIndentedString(original)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}