/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.tvshows.model

import com.google.gson.annotations.SerializedName
import io.swagger.v3.oas.annotations.media.Schema
import java.util.*

/**
 * LinksSelf
 */
class LinksSelf {
    /**
     * Get href
     * @return href
     */
    @get:Schema(required = true, description = "")
    @SerializedName("href")
    var href: String? = null
    fun href(href: String?): LinksSelf {
        this.href = href
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val linksSelf = o as LinksSelf
        return href == linksSelf.href
    }

    override fun hashCode(): Int {
        return Objects.hash(href)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class LinksSelf {\n")
        sb.append("    href: ").append(toIndentedString(href)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}