/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.bme.aut.tvshows.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Links
 */

public class Links {
  @SerializedName("self")
  private LinksSelf self = null;

  @SerializedName("previousepisode")
  private LinksSelf previousepisode = null;

  public Links self(LinksSelf self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @Schema(required = true, description = "")
  public LinksSelf getSelf() {
    return self;
  }

  public void setSelf(LinksSelf self) {
    this.self = self;
  }

  public Links previousepisode(LinksSelf previousepisode) {
    this.previousepisode = previousepisode;
    return this;
  }

   /**
   * Get previousepisode
   * @return previousepisode
  **/
  @Schema(description = "")
  public LinksSelf getPreviousepisode() {
    return previousepisode;
  }

  public void setPreviousepisode(LinksSelf previousepisode) {
    this.previousepisode = previousepisode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Links links = (Links) o;
    return Objects.equals(this.self, links.self) &&
        Objects.equals(this.previousepisode, links.previousepisode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, previousepisode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Links {\n");
    
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    previousepisode: ").append(toIndentedString(previousepisode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
