/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.tvshows.model

import com.google.gson.annotations.SerializedName
import io.swagger.v3.oas.annotations.media.Schema
import java.math.BigDecimal
import java.util.*

/**
 * Network
 */
class Network {
    /**
     * Get id
     * @return id
     */
    @get:Schema(required = true, description = "")
    @SerializedName("id")
    var id: BigDecimal? = null

    /**
     * Get name
     * @return name
     */
    @get:Schema(required = true, description = "")
    @SerializedName("name")
    var name: String? = null

    /**
     * Get country
     * @return country
     */
    @get:Schema(required = true, description = "")
    @SerializedName("country")
    var country: Country? = null
    fun id(id: BigDecimal?): Network {
        this.id = id
        return this
    }

    fun name(name: String?): Network {
        this.name = name
        return this
    }

    fun country(country: Country?): Network {
        this.country = country
        return this
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null || javaClass != other.javaClass) {
            return false
        }
        val network = other as Network
        return id == network.id &&
                name == network.name &&
                country == network.country
    }

    override fun hashCode(): Int {
        return Objects.hash(id, name, country)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class Network {\n")
        sb.append("    id: ").append(toIndentedString(id)).append("\n")
        sb.append("    name: ").append(toIndentedString(name)).append("\n")
        sb.append("    country: ").append(toIndentedString(country)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}