/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.tvshows.model

import com.google.gson.annotations.SerializedName
import io.swagger.v3.oas.annotations.media.Schema
import java.util.*

/**
 * PersonData
 */
class PersonData {
    /**
     * Get name
     * @return name
     */
    @get:Schema(required = true, description = "")
    @SerializedName("name")
    var name: String? = null

    /**
     * Get country
     * @return country
     */
    @get:Schema(required = true, description = "")
    @SerializedName("country")
    var country: Country? = null

    /**
     * Get birthday
     * @return birthday
     */
    @get:Schema(required = true, description = "")
    @SerializedName("birthday")
    var birthday: String? = null

    /**
     * Get deathday
     * @return deathday
     */
    @get:Schema(description = "")
    @SerializedName("deathday")
    var deathday: Any? = null

    /**
     * Get gender
     * @return gender
     */
    @get:Schema(required = true, description = "")
    @SerializedName("gender")
    var gender: String? = null

    /**
     * Get image
     * @return image
     */
    @get:Schema(description = "")
    @SerializedName("image")
    var image: Image? = null
    fun name(name: String?): PersonData {
        this.name = name
        return this
    }

    fun country(country: Country?): PersonData {
        this.country = country
        return this
    }

    fun birthday(birthday: String?): PersonData {
        this.birthday = birthday
        return this
    }

    fun deathday(deathday: Any?): PersonData {
        this.deathday = deathday
        return this
    }

    fun gender(gender: String?): PersonData {
        this.gender = gender
        return this
    }

    fun image(image: Image?): PersonData {
        this.image = image
        return this
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null || javaClass != other.javaClass) {
            return false
        }
        val personData = other as PersonData
        return name == personData.name &&
                country == personData.country &&
                birthday == personData.birthday &&
                deathday == personData.deathday &&
                gender == personData.gender &&
                image == personData.image
    }

    override fun hashCode(): Int {
        return Objects.hash(name, country, birthday, deathday, gender, image)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class PersonData {\n")
        sb.append("    name: ").append(toIndentedString(name)).append("\n")
        sb.append("    country: ").append(toIndentedString(country)).append("\n")
        sb.append("    birthday: ").append(toIndentedString(birthday)).append("\n")
        sb.append("    deathday: ").append(toIndentedString(deathday)).append("\n")
        sb.append("    gender: ").append(toIndentedString(gender)).append("\n")
        sb.append("    image: ").append(toIndentedString(image)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}