/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.tvshows.model

import com.google.gson.annotations.SerializedName
import io.swagger.v3.oas.annotations.media.Schema
import java.math.BigDecimal
import java.util.*

/**
 * Rating
 */
class Rating {
    /**
     * Get average
     * @return average
     */
    @get:Schema(required = true, description = "")
    @SerializedName("average")
    var average: BigDecimal? = null
    fun average(average: BigDecimal?): Rating {
        this.average = average
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val rating = o as Rating
        return average == rating.average
    }

    override fun hashCode(): Int {
        return Objects.hash(average)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class Rating {\n")
        sb.append("    average: ").append(toIndentedString(average)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}