/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.tvshows.model

import com.google.gson.annotations.SerializedName
import io.swagger.v3.oas.annotations.media.Schema
import java.math.BigDecimal
import java.util.*

/**
 * SeasonData
 */
class SeasonData {
    /**
     * Get number
     * @return number
     */
    @get:Schema(required = true, description = "")
    @SerializedName("number")
    var number: BigDecimal? = null

    /**
     * Get name
     * @return name
     */
    @get:Schema(required = true, description = "")
    @SerializedName("name")
    var name: String? = null

    /**
     * Get episodeOrder
     * @return episodeOrder
     */
    @get:Schema(required = true, description = "")
    @SerializedName("episodeOrder")
    var episodeOrder: BigDecimal? = null

    /**
     * Get premiereDate
     * @return premiereDate
     */
    @get:Schema(required = true, description = "")
    @SerializedName("premiereDate")
    var premiereDate: String? = null

    /**
     * Get endDate
     * @return endDate
     */
    @get:Schema(required = true, description = "")
    @SerializedName("endDate")
    var endDate: String? = null

    /**
     * Get network
     * @return network
     */
    @get:Schema(required = true, description = "")
    @SerializedName("network")
    var network: Network? = null

    /**
     * Get webChannel
     * @return webChannel
     */
    @get:Schema(description = "")
    @SerializedName("webChannel")
    var webChannel: Any? = null

    /**
     * Get image
     * @return image
     */
    @get:Schema(required = true, description = "")
    @SerializedName("image")
    var image: Image? = null

    /**
     * Get summary
     * @return summary
     */
    @get:Schema(required = true, description = "")
    @SerializedName("summary")
    var summary: String? = null
    fun number(number: BigDecimal?): SeasonData {
        this.number = number
        return this
    }

    fun name(name: String?): SeasonData {
        this.name = name
        return this
    }

    fun episodeOrder(episodeOrder: BigDecimal?): SeasonData {
        this.episodeOrder = episodeOrder
        return this
    }

    fun premiereDate(premiereDate: String?): SeasonData {
        this.premiereDate = premiereDate
        return this
    }

    fun endDate(endDate: String?): SeasonData {
        this.endDate = endDate
        return this
    }

    fun network(network: Network?): SeasonData {
        this.network = network
        return this
    }

    fun webChannel(webChannel: Any?): SeasonData {
        this.webChannel = webChannel
        return this
    }

    fun image(image: Image?): SeasonData {
        this.image = image
        return this
    }

    fun summary(summary: String?): SeasonData {
        this.summary = summary
        return this
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null || javaClass != other.javaClass) {
            return false
        }
        val seasonData = other as SeasonData
        return number == seasonData.number &&
                name == seasonData.name &&
                episodeOrder == seasonData.episodeOrder &&
                premiereDate == seasonData.premiereDate &&
                endDate == seasonData.endDate &&
                network == seasonData.network &&
                webChannel == seasonData.webChannel &&
                image == seasonData.image &&
                summary == seasonData.summary
    }

    override fun hashCode(): Int {
        return Objects.hash(
            number,
            name,
            episodeOrder,
            premiereDate,
            endDate,
            network,
            webChannel,
            image,
            summary
        )
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class SeasonData {\n")
        sb.append("    number: ").append(toIndentedString(number)).append("\n")
        sb.append("    name: ").append(toIndentedString(name)).append("\n")
        sb.append("    episodeOrder: ").append(toIndentedString(episodeOrder)).append("\n")
        sb.append("    premiereDate: ").append(toIndentedString(premiereDate)).append("\n")
        sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n")
        sb.append("    network: ").append(toIndentedString(network)).append("\n")
        sb.append("    webChannel: ").append(toIndentedString(webChannel)).append("\n")
        sb.append("    image: ").append(toIndentedString(image)).append("\n")
        sb.append("    summary: ").append(toIndentedString(summary)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}