/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.bme.aut.tvshows.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Season
 */

public class Season {
  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("number")
  private BigDecimal number = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("episodeOrder")
  private BigDecimal episodeOrder = null;

  @SerializedName("premiereDate")
  private String premiereDate = null;

  @SerializedName("endDate")
  private String endDate = null;

  @SerializedName("network")
  private Network network = null;

  @SerializedName("webChannel")
  private Object webChannel = null;

  @SerializedName("image")
  private Image image = null;

  @SerializedName("summary")
  private Object summary = null;

  @SerializedName("_links")
  private SeasonLinks _links = null;

  public Season id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public Season url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(required = true, description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Season number(BigDecimal number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @Schema(required = true, description = "")
  public BigDecimal getNumber() {
    return number;
  }

  public void setNumber(BigDecimal number) {
    this.number = number;
  }

  public Season name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Season episodeOrder(BigDecimal episodeOrder) {
    this.episodeOrder = episodeOrder;
    return this;
  }

   /**
   * Get episodeOrder
   * @return episodeOrder
  **/
  @Schema(required = true, description = "")
  public BigDecimal getEpisodeOrder() {
    return episodeOrder;
  }

  public void setEpisodeOrder(BigDecimal episodeOrder) {
    this.episodeOrder = episodeOrder;
  }

  public Season premiereDate(String premiereDate) {
    this.premiereDate = premiereDate;
    return this;
  }

   /**
   * Get premiereDate
   * @return premiereDate
  **/
  @Schema(required = true, description = "")
  public String getPremiereDate() {
    return premiereDate;
  }

  public void setPremiereDate(String premiereDate) {
    this.premiereDate = premiereDate;
  }

  public Season endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @Schema(required = true, description = "")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public Season network(Network network) {
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @Schema(required = true, description = "")
  public Network getNetwork() {
    return network;
  }

  public void setNetwork(Network network) {
    this.network = network;
  }

  public Season webChannel(Object webChannel) {
    this.webChannel = webChannel;
    return this;
  }

   /**
   * Get webChannel
   * @return webChannel
  **/
  @Schema(description = "")
  public Object getWebChannel() {
    return webChannel;
  }

  public void setWebChannel(Object webChannel) {
    this.webChannel = webChannel;
  }

  public Season image(Image image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @Schema(required = true, description = "")
  public Image getImage() {
    return image;
  }

  public void setImage(Image image) {
    this.image = image;
  }

  public Season summary(Object summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @Schema(description = "")
  public Object getSummary() {
    return summary;
  }

  public void setSummary(Object summary) {
    this.summary = summary;
  }

  public Season _links(SeasonLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(required = true, description = "")
  public SeasonLinks getLinks() {
    return _links;
  }

  public void setLinks(SeasonLinks _links) {
    this._links = _links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Season season = (Season) o;
    return Objects.equals(this.id, season.id) &&
        Objects.equals(this.url, season.url) &&
        Objects.equals(this.number, season.number) &&
        Objects.equals(this.name, season.name) &&
        Objects.equals(this.episodeOrder, season.episodeOrder) &&
        Objects.equals(this.premiereDate, season.premiereDate) &&
        Objects.equals(this.endDate, season.endDate) &&
        Objects.equals(this.network, season.network) &&
        Objects.equals(this.webChannel, season.webChannel) &&
        Objects.equals(this.image, season.image) &&
        Objects.equals(this.summary, season.summary) &&
        Objects.equals(this._links, season._links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, number, name, episodeOrder, premiereDate, endDate, network, webChannel, image, summary, _links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Season {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    episodeOrder: ").append(toIndentedString(episodeOrder)).append("\n");
    sb.append("    premiereDate: ").append(toIndentedString(premiereDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    webChannel: ").append(toIndentedString(webChannel)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
