/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.bme.aut.tvshows.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SeasonData
 */

public class SeasonData {
  @SerializedName("number")
  private BigDecimal number = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("episodeOrder")
  private BigDecimal episodeOrder = null;

  @SerializedName("premiereDate")
  private String premiereDate = null;

  @SerializedName("endDate")
  private String endDate = null;

  @SerializedName("network")
  private Network network = null;

  @SerializedName("webChannel")
  private Object webChannel = null;

  @SerializedName("image")
  private Image image = null;

  @SerializedName("summary")
  private String summary = null;

  public SeasonData number(BigDecimal number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @Schema(required = true, description = "")
  public BigDecimal getNumber() {
    return number;
  }

  public void setNumber(BigDecimal number) {
    this.number = number;
  }

  public SeasonData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SeasonData episodeOrder(BigDecimal episodeOrder) {
    this.episodeOrder = episodeOrder;
    return this;
  }

   /**
   * Get episodeOrder
   * @return episodeOrder
  **/
  @Schema(required = true, description = "")
  public BigDecimal getEpisodeOrder() {
    return episodeOrder;
  }

  public void setEpisodeOrder(BigDecimal episodeOrder) {
    this.episodeOrder = episodeOrder;
  }

  public SeasonData premiereDate(String premiereDate) {
    this.premiereDate = premiereDate;
    return this;
  }

   /**
   * Get premiereDate
   * @return premiereDate
  **/
  @Schema(required = true, description = "")
  public String getPremiereDate() {
    return premiereDate;
  }

  public void setPremiereDate(String premiereDate) {
    this.premiereDate = premiereDate;
  }

  public SeasonData endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @Schema(required = true, description = "")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public SeasonData network(Network network) {
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @Schema(required = true, description = "")
  public Network getNetwork() {
    return network;
  }

  public void setNetwork(Network network) {
    this.network = network;
  }

  public SeasonData webChannel(Object webChannel) {
    this.webChannel = webChannel;
    return this;
  }

   /**
   * Get webChannel
   * @return webChannel
  **/
  @Schema(description = "")
  public Object getWebChannel() {
    return webChannel;
  }

  public void setWebChannel(Object webChannel) {
    this.webChannel = webChannel;
  }

  public SeasonData image(Image image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @Schema(required = true, description = "")
  public Image getImage() {
    return image;
  }

  public void setImage(Image image) {
    this.image = image;
  }

  public SeasonData summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @Schema(required = true, description = "")
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeasonData seasonData = (SeasonData) o;
    return Objects.equals(this.number, seasonData.number) &&
        Objects.equals(this.name, seasonData.name) &&
        Objects.equals(this.episodeOrder, seasonData.episodeOrder) &&
        Objects.equals(this.premiereDate, seasonData.premiereDate) &&
        Objects.equals(this.endDate, seasonData.endDate) &&
        Objects.equals(this.network, seasonData.network) &&
        Objects.equals(this.webChannel, seasonData.webChannel) &&
        Objects.equals(this.image, seasonData.image) &&
        Objects.equals(this.summary, seasonData.summary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, name, episodeOrder, premiereDate, endDate, network, webChannel, image, summary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeasonData {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    episodeOrder: ").append(toIndentedString(episodeOrder)).append("\n");
    sb.append("    premiereDate: ").append(toIndentedString(premiereDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    webChannel: ").append(toIndentedString(webChannel)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
