/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.bme.aut.tvshows.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ShowSearchResult
 */

public class ShowSearchResult {
  @SerializedName("score")
  private BigDecimal score = null;

  @SerializedName("show")
  private ShowSummary show = null;

  public ShowSearchResult score(BigDecimal score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @Schema(required = true, description = "")
  public BigDecimal getScore() {
    return score;
  }

  public void setScore(BigDecimal score) {
    this.score = score;
  }

  public ShowSearchResult show(ShowSummary show) {
    this.show = show;
    return this;
  }

   /**
   * Get show
   * @return show
  **/
  @Schema(required = true, description = "")
  public ShowSummary getShow() {
    return show;
  }

  public void setShow(ShowSummary show) {
    this.show = show;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowSearchResult showSearchResult = (ShowSearchResult) o;
    return Objects.equals(this.score, showSearchResult.score) &&
        Objects.equals(this.show, showSearchResult.show);
  }

  @Override
  public int hashCode() {
    return Objects.hash(score, show);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowSearchResult {\n");
    
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    show: ").append(toIndentedString(show)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
