/*
 * TVMaze
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.bme.aut.tvshows.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ShowData
 */

public class ShowData {
  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("genres")
  private List<String> genres = new ArrayList<String>();

  @SerializedName("status")
  private String status = null;

  @SerializedName("runtime")
  private BigDecimal runtime = null;

  @SerializedName("premiered")
  private String premiered = null;

  @SerializedName("officialSite")
  private String officialSite = null;

  @SerializedName("schedule")
  private Schedule schedule = null;

  @SerializedName("rating")
  private Rating rating = null;

  @SerializedName("weight")
  private BigDecimal weight = null;

  @SerializedName("network")
  private Network network = null;

  @SerializedName("webChannel")
  private Object webChannel = null;

  @SerializedName("dvdCountry")
  private Object dvdCountry = null;

  @SerializedName("externals")
  private Externals externals = null;

  @SerializedName("image")
  private Image image = null;

  @SerializedName("summary")
  private String summary = null;

  @SerializedName("updated")
  private BigDecimal updated = null;

  public ShowData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ShowData type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ShowData language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @Schema(required = true, description = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public ShowData genres(List<String> genres) {
    this.genres = genres;
    return this;
  }

  public ShowData addGenresItem(String genresItem) {
    this.genres.add(genresItem);
    return this;
  }

   /**
   * Get genres
   * @return genres
  **/
  @Schema(required = true, description = "")
  public List<String> getGenres() {
    return genres;
  }

  public void setGenres(List<String> genres) {
    this.genres = genres;
  }

  public ShowData status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ShowData runtime(BigDecimal runtime) {
    this.runtime = runtime;
    return this;
  }

   /**
   * Get runtime
   * @return runtime
  **/
  @Schema(required = true, description = "")
  public BigDecimal getRuntime() {
    return runtime;
  }

  public void setRuntime(BigDecimal runtime) {
    this.runtime = runtime;
  }

  public ShowData premiered(String premiered) {
    this.premiered = premiered;
    return this;
  }

   /**
   * Get premiered
   * @return premiered
  **/
  @Schema(required = true, description = "")
  public String getPremiered() {
    return premiered;
  }

  public void setPremiered(String premiered) {
    this.premiered = premiered;
  }

  public ShowData officialSite(String officialSite) {
    this.officialSite = officialSite;
    return this;
  }

   /**
   * Get officialSite
   * @return officialSite
  **/
  @Schema(required = true, description = "")
  public String getOfficialSite() {
    return officialSite;
  }

  public void setOfficialSite(String officialSite) {
    this.officialSite = officialSite;
  }

  public ShowData schedule(Schedule schedule) {
    this.schedule = schedule;
    return this;
  }

   /**
   * Get schedule
   * @return schedule
  **/
  @Schema(required = true, description = "")
  public Schedule getSchedule() {
    return schedule;
  }

  public void setSchedule(Schedule schedule) {
    this.schedule = schedule;
  }

  public ShowData rating(Rating rating) {
    this.rating = rating;
    return this;
  }

   /**
   * Get rating
   * @return rating
  **/
  @Schema(required = true, description = "")
  public Rating getRating() {
    return rating;
  }

  public void setRating(Rating rating) {
    this.rating = rating;
  }

  public ShowData weight(BigDecimal weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  @Schema(required = true, description = "")
  public BigDecimal getWeight() {
    return weight;
  }

  public void setWeight(BigDecimal weight) {
    this.weight = weight;
  }

  public ShowData network(Network network) {
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @Schema(required = true, description = "")
  public Network getNetwork() {
    return network;
  }

  public void setNetwork(Network network) {
    this.network = network;
  }

  public ShowData webChannel(Object webChannel) {
    this.webChannel = webChannel;
    return this;
  }

   /**
   * Get webChannel
   * @return webChannel
  **/
  @Schema(description = "")
  public Object getWebChannel() {
    return webChannel;
  }

  public void setWebChannel(Object webChannel) {
    this.webChannel = webChannel;
  }

  public ShowData dvdCountry(Object dvdCountry) {
    this.dvdCountry = dvdCountry;
    return this;
  }

   /**
   * Get dvdCountry
   * @return dvdCountry
  **/
  @Schema(description = "")
  public Object getDvdCountry() {
    return dvdCountry;
  }

  public void setDvdCountry(Object dvdCountry) {
    this.dvdCountry = dvdCountry;
  }

  public ShowData externals(Externals externals) {
    this.externals = externals;
    return this;
  }

   /**
   * Get externals
   * @return externals
  **/
  @Schema(required = true, description = "")
  public Externals getExternals() {
    return externals;
  }

  public void setExternals(Externals externals) {
    this.externals = externals;
  }

  public ShowData image(Image image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @Schema(description = "")
  public Image getImage() {
    return image;
  }

  public void setImage(Image image) {
    this.image = image;
  }

  public ShowData summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @Schema(required = true, description = "")
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public ShowData updated(BigDecimal updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @Schema(required = true, description = "")
  public BigDecimal getUpdated() {
    return updated;
  }

  public void setUpdated(BigDecimal updated) {
    this.updated = updated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowData showData = (ShowData) o;
    return Objects.equals(this.name, showData.name) &&
        Objects.equals(this.type, showData.type) &&
        Objects.equals(this.language, showData.language) &&
        Objects.equals(this.genres, showData.genres) &&
        Objects.equals(this.status, showData.status) &&
        Objects.equals(this.runtime, showData.runtime) &&
        Objects.equals(this.premiered, showData.premiered) &&
        Objects.equals(this.officialSite, showData.officialSite) &&
        Objects.equals(this.schedule, showData.schedule) &&
        Objects.equals(this.rating, showData.rating) &&
        Objects.equals(this.weight, showData.weight) &&
        Objects.equals(this.network, showData.network) &&
        Objects.equals(this.webChannel, showData.webChannel) &&
        Objects.equals(this.dvdCountry, showData.dvdCountry) &&
        Objects.equals(this.externals, showData.externals) &&
        Objects.equals(this.image, showData.image) &&
        Objects.equals(this.summary, showData.summary) &&
        Objects.equals(this.updated, showData.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, language, genres, status, runtime, premiered, officialSite, schedule, rating, weight, network, webChannel, dvdCountry, externals, image, summary, updated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowData {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    genres: ").append(toIndentedString(genres)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    runtime: ").append(toIndentedString(runtime)).append("\n");
    sb.append("    premiered: ").append(toIndentedString(premiered)).append("\n");
    sb.append("    officialSite: ").append(toIndentedString(officialSite)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    webChannel: ").append(toIndentedString(webChannel)).append("\n");
    sb.append("    dvdCountry: ").append(toIndentedString(dvdCountry)).append("\n");
    sb.append("    externals: ").append(toIndentedString(externals)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
